version: '3.9'

services:
  db_contratos:
    image: postgres:16
    container_name: contratos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contratos
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: contratos_api
    ports:
      - '3001:3001'
      - '5555:5555'
    depends_on:
      - db_contratos
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db_contratos:5432/contratos
      - PORT=3001
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
